export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const BRON_ROUTE = '/bron'
export const BLOG_ROUTE = '/blog'
export const MAIN_ROUTE = '/main'